"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_routes_1 = require("./auth-routes");
var index_1 = require("./api/index");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.use('/auth', auth_routes_1.default);
router.use('/api', auth_1.authenticateToken, index_1.default);
exports.default = router;
